// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubAgentTerminalStatus } from "../SubAgentTerminalStatus";

/**
 * Live terminal transition for a direct child sub-agent. This notification is intentionally
 * not represented as a thread item and is not replayed from thread history.
 */
export type SubAgentTerminalNotification = {
/**
 * Parent thread receiving this live notification.
 */
threadId: string, agentThreadId: string, agentPath: string | null, agentNickname: string | null, agentRole: string | null, harness: string | null, model: string | null, status: SubAgentTerminalStatus, };
